server:
  port: 8095

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service_db
    username: postgres
    password: 1234  # Utilisez un mot de passe plus sécurisé
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    instance:
      preferIpAddress: true
