server:
  port: 8086

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

stripe:
  api:
    secret-key: sk_test_51QVfdtKycUC9MuJlVXENy5FiCixevJpVimucQXfmL3KjUqNK3iJmqvs6Vcsmlnj040EG1rQzl63KK07aWksfMpzR00U4yLmXOl


